---
env:
  global:
  - OS="${TRAVIS_OS_NAME}"
  - VERSION="${TRAVIS_TAG}"
  - NAME=Detect4j
  - DETECTOR_AGENT_VERSION="v1.0.0-alpha.2"
  - DETECTOR_JVM_TARGET_PATTERN=".*Detect4j.*"
  - DETECTOR_SCAN_INTERVAL=5
  - DETECTOR_TIMEOUT=30

# # language: java
# jdk:
# - openjdk8
#   # - openjdk9
#   # - openjdk10
#   # - openjdk11
# os:
# - linux
# # - windows

install: true
before_install:
- chmod +x scripts/build.sh scripts/test.sh
before_script: scripts/build.sh
script: scripts/test.sh

jobs:
  include:
  # - stage: test
  #   language: java
  #   jdk: openjdk8
  #   os: linux
  - stage: test
    language: shell
    os: windows
    env: YARN_GPG=no
    before_install:
    - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
    - export PATH=${JAVA_HOME}/bin:${PATH}
    - choco install openjdk8 -params 'installdir=c:\\jdk' -y
    - choco install gradle --version=5.1
    - gradle -version
  - stage: deploy
    # before_install:
    # - chmod +x scripts/build.sh scripts/test.sh
    # install: true
    # jdk: openjdk8
    # before_script: scripts/build.sh
    # script: scripts/test.sh
    deploy:
      provider: releases
      api_key:
        secure: WP+Dzf61Y7RpB3YEMzJdppWFuMdztEhmBVHgpIOE5a4Bd0xwgGGRpf8ESpoM/yjQ9etYLavqZ8Zsvc+2f5QKvWsWVC3J6M3IcicLH3Fbc0wwv3v1YmzX0xhfgpFM8T500BXiMkuvyT8k6av2KDI/Woz7bQqPK1inS0Otsdp04BAQTiCqz+vT9SI3I0WBGLEh/rKkPOGecOWqPVkOlz+jJNoRG9DUnQ/rHVlVy7a1zg4vkyvVnYIa5cAWsE+dbPvgwy3bJ3uURkO2MfixL8faTQrWfVMFT6TREEYp2UpU+ndzWOpVMu4uqdxJPzF69BOYjXg1TIMRaw3iej0PQE6dW8gnJ4s1QzCc1tyJBEJ3IRWFycIta1zm9uP8NjTaLQUX5mJBDzNC7Nl/e3BILmoT7NqqcaLJ7vziUXKhfiYLUk5QynSuAQH75gNjzPlBaIS8aV5lHF4IyrGvtGj9CKos2K7qUiUY1ogSh8f6FND+Cw2tDzhDEQkL4rLBejviNwkVGOGjvs2+3i3lZ/SM5Jo4N1EDaYadaceecafA2Jcjr3aCqOL04VXeSxcJ5FcqoFTE644EduAaOpmGsyFPDh2/pWqnEF3ZCtK/fWS8nt0CPjLdVtS/5Uk56U7Ni2/yhuqF4Nvpc+nEQ7VuIMgg7cSMTsEYfQ+Xe//iV7b8rr27boU=
      file_glob: true
      file:
      - build/libs/*
      skip_cleanup: true
      on:
        repo: theque5t/Detect4j
        tags: true
